In [1]:
import numpy as np 

In [2]:
list1 = [10, 20, 30]
list1

[10, 20, 30]

In [4]:
arr1 = np.array(list1)
type(arr1)

numpy.ndarray

In [25]:
arr2 = np.arange(10, 20, 2)
arr2

array([10, 12, 14, 16, 18])

In [6]:
list2 = [40, 50, 60]
list2

[40, 50, 60]

In [7]:
list3 = [list1, list2]
list3

[[10, 20, 30], [40, 50, 60]]

In [8]:
# making a 2d array from list list
arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [13]:
# Get rows and columns
arr3.shape

(2, 3)

In [14]:
arr4 = np.array([[[1,2,3],[4,5,6]],
                 [[7,8,9],[2,3,4]]])
arr4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [2, 3, 4]]])

In [15]:
arr4.shape

(2, 2, 3)

In [16]:
list1 * 3

[10, 20, 30, 10, 20, 30, 10, 20, 30]

In [17]:
arr1 * 3

array([30, 60, 90])

In [18]:
arr4 * 3

array([[[ 3,  6,  9],
        [12, 15, 18]],

       [[21, 24, 27],
        [ 6,  9, 12]]])

In [21]:
arr2 = np.array(list2)
arr2

array([40, 50, 60])

In [22]:
arr1

array([10, 20, 30])

In [26]:
arr2

array([10, 12, 14, 16, 18])

In [27]:
arr1 * arr2

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

## Activity :  
a)1d 12elements (12,)  
b)2d (3,4)  
c)3d (2,5,4)  

In [28]:
list1 = [i for i in range(1,13)]
arr1 = np.array(list1)
print(arr1)
print(arr1.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [29]:
list2 = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
arr2 = np.array(list2)
print(arr2)
print(arr2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [30]:
list3 = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]],
        [[21, 22, 23, 24], [25, 26, 27, 28], [29, 30, 31, 32], [33, 34, 35, 36], [37, 38, 39, 40]]]
arr3 = np.array(list3)
print(arr3)
print(arr3.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]
  [17 18 19 20]]

 [[21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]
  [37 38 39 40]]]
(2, 5, 4)


In [32]:
arr2[2,3] # Work same as lists

12

In [33]:
arr2.sum()


78

In [35]:
arr2.sum(1) # 0 means comlumn wise, 1 means row wise

array([10, 26, 42])

In [36]:
# mean , max , min work same as sum

In [37]:
arr1 = np.array([10,20,30])

In [42]:
for x in arr1:
    print(x)

10
20
30


In [43]:
for x in np.nditer(arr3):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
